#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

PROG=/root/bin/nezha-agent
SERVER=
PASSWORD=

start_service() {
    procd_open_instance
    procd_set_param command "$PROG" -s "$SERVER" -p "$PASSWORD" --report-delay 3
    procd_append_param command --disable-auto-update --disable-command-execute --disable-force-update
    procd_append_param command --skip-conn --skip-procs
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
