#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

PROG=/root/bin/phantun_server
PORT=51822
SERVER=127.0.0.1:51820

start_service() {
    procd_open_instance
    procd_set_param command "$PROG" -l "$PORT" -r "$SERVER" --tun phantun
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
