#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

PROG=/root/bin/wstunnel
SERVER=

start_service() {
    procd_open_instance
    procd_set_param command "$PROG" -L 127.0.0.1:51080:127.0.0.1:51820
    procd_append_param command --udp
    procd_append_param command --upgradePathPrefix=/wireguard
    procd_append_param command "$SERVER"
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
